name: Metadata-Manager-CI

on: [push, pull_request]

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    name: Build Metadata-Manager ( ${{ matrix.os }} )
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:${{ matrix.os }}
      volumes:
        - ${{ vars.ccache_dir }}:${{ vars.ccache_dir }}
    defaults:
      run:
        shell: bash
    env:
      BUILD_TYPE: ''

    steps:
      - name: Make_CI_Directory_Postgresql
        run: |
          cd ${GITHUB_WORKSPACE}
          rm -rf ci_test
          mkdir ci_test

      - name: Checkout_Postgresql
        uses: actions/checkout@v3
        with:
          path: ci_test
          submodules: true
          token: ${{ secrets.GHA_PAT }}

      - name: CMake_Build_metadata-manager_Postgresql
        run: |
          cd ${GITHUB_WORKSPACE}/ci_test
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DFORCE_INSTALL_RPATH=ON -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j8

      - name: Cleanup_Postgresql
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.local/
          rm -rf ${GITHUB_WORKSPACE}/ci_test

      - name: Make_CI_Directory_Json
        run: |
          cd ${GITHUB_WORKSPACE}
          rm -rf ci_test2
          mkdir ci_test2

      - name: Checkout_Json
        uses: actions/checkout@v3
        with:
          path: ci_test2
          submodules: true
          token: ${{ secrets.GHA_PAT }}

      - name: CMake_Build_metadata-manager_Json
        run: |
          cd ${GITHUB_WORKSPACE}/ci_test2
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DFORCE_INSTALL_RPATH=ON -DDATA_STORAGE=json -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/.local ..
          cmake --build . --target install --clean-first -- -j8
          make
          make install

      - name: Cleanup_Json
        run: |
          rm -rf ${GITHUB_WORKSPACE}/.local/
          rm -rf ${GITHUB_WORKSPACE}/ci_test2
